-- Create database, schemas, and basic roles (edit names as needed)

CREATE OR REPLACE DATABASE FLEET_MONITORING;
CREATE OR REPLACE SCHEMA FLEET_MONITORING.RAW;
CREATE OR REPLACE SCHEMA FLEET_MONITORING.CLEAN;
CREATE OR REPLACE SCHEMA FLEET_MONITORING.ANALYTICS;
